# Generated by Django 5.0.6 on 2024-05-30 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_alter_todo_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
                ('created_at', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
