# Generated by Django 5.0.6 on 2024-05-30 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_transaction_delete_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.CharField(max_length=200),
        ),
    ]
